# Server port
server:
  port: 80
# Spring Setting Start
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
# Datasource ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  # JPA
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  # ThymeLeaf
  thymeleaf:
    check-template-location: true
    suffix: .html
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    mode: html
#    template-resolver-order: 0
  # Dev-Tools
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  freemarker:
    cache: false