# H2 ??
spring:
  h2:
    console:
      enabled: true
      path: /h2
# Datasource ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/D:/Git/Spring-library-edu/DB/h2
    username: wooj
    password: 1234
# JPA
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  # ????
  thymeleaf:
    cache: false
# Dev-Tools
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true



